### ISSUE TITLE
Commands dissapear after first run

### ISSUE THREAD

**Issue by FireController1847** [vik1395/ProtectionStones-Minecraft#1]
Main culprit: /ps addowner
Works first time, second time it says no such command.

Broken Commands: /ps view
Never works, ever.

/ps info
Will not error saying on such command, but will error if you put in a value such as members, owners, flags.

**Comment by Dragoboss** [comment]
Problem seems to lie in support for CraftBukkit.
Must fix backwards compatibility with CraftBukkit while not breaking Spigot support.

What Minecraft version is your server currently on?

**Comment by Dragoboss** [comment]
Did some testing on CraftBukkit-1.10.2-R0.1
I seem to have no issues with the plugin at all, no errors, all commands work.

What server version are you using and which versions of PStones?
Without this info I cannot further help you...

**Comment by 12irexTM** [comment]
I have same problem too.
I use spigot-1.8.8-R0.1 for my server.

**Comment by vik1395** [comment]
The latest version (1.4.1) of the plugin is built based on Spigot 1.10
You might want to use [ProtectionStones-1.3.2](https://www.spigotmc.org/resources/protectionstones.10096/download?version=48165) for Spigot 1.8
