### ISSUE TITLE
/ps flag

### ISSUE THREAD

**Issue by arturek1666** [vik1395/ProtectionStones-Minecraft#10]
/ps flag dosn't work people get error. Please fix, No evidence as there is nothing else

**Comment by Dragoboss** [comment]
Alright here we go again:
Please give me a http://pastebin.com entry of your config.
Also look if there is any console error, is so, pastebin that too.

And please define the error people get.
Additionally, can you tell me the version of PStones you're using and the server version+mod you are on?

Without any of this information there is no way for either of us to help you.

**Comment by ElkpojoacoTwo** [comment]
http://pastebin.com/xhQp1sLn

**Comment by Dragoboss** [comment]
@ElkpojoacoTwo
As mentioned in the other issue report, use the worldguard 6.1.3 version.
