### ISSUE TITLE
use not working

### ISSUE THREAD

**Issue by tads421** [vik1395/ProtectionStones-Minecraft#11]
Good Afternoon, once my players place the PSTONE they can no longer open doors, use chests or crafting tables.

How can i fix this?

**Comment by Dragoboss** [comment]
That is because per default (changeable in the config), when a PStone is placed, the 'use' WorldGuard flag is set to 'deny'.
Have your players do /ps flag use allow, to re-enable usage of doors and such.
Might want to make that the default in the config too.
