### ISSUE TITLE
/ps flag Not working...

### ISSUE THREAD

**Issue by RTCFlyer** [vik1395/ProtectionStones-Minecraft#14]
Hi, i am running the latest version of your plugin and I am also running paperspigot 1.11.2 
I get this error whenever I do /ps flag

Error:

3.02 17:18:03 [Server] INFO RTCFlyer issued server command: /ps flag test allow
23.02 17:18:03 [Server] ERROR null
23.02 17:18:03 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'ps' in plugin ProtectionStones v1.4.1
23.02 17:18:03 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[paperspigot-1.11.2.jar:git-Paper-1021]
23.02 17:18:03 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151) ~[paperspigot-1.11.2.jar:git-Paper-1021]
23.02 17:18:03 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:674) ~[paperspigot-1.11.2.jar:git-Paper-1021]
23.02 17:18:03 [Server] INFO at net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerConnection.java:1383) [paperspigot-1.11.2.jar:git-Paper-1021]
23.02 17:18:03 [Server] INFO at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1188) [paperspigot-1.11.2.jar:git-Paper-1021]
23.02 17:18:03 [Server] INFO at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [paperspigot-1.11.2.jar:git-Paper-1021]
23.02 17:18:03 [Server] INFO at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) [paperspigot-1.11.2.jar:git-Paper-1021]
23.02 17:18:03 [Server] INFO at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [paperspigot-1.11.2.jar:git-Paper-1021]
23.02 17:18:03 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_112]
23.02 17:18:03 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_112]
23.02 17:18:03 [Server] INFO at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [paperspigot-1.11.2.jar:git-Paper-1021]
23.02 17:18:03 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:821) [paperspigot-1.11.2.jar:git-Paper-1021]
23.02 17:18:03 [Server] INFO at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:403) [paperspigot-1.11.2.jar:git-Paper-1021]
23.02 17:18:03 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:749) [paperspigot-1.11.2.jar:git-Paper-1021]
23.02 17:18:03 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:648) [paperspigot-1.11.2.jar:git-Paper-1021]
23.02 17:18:03 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
23.02 17:18:03 [Server] INFO Caused by: java.lang.NoSuchMethodError: com.sk89q.worldguard.protection.flags.DefaultFlag.fuzzyMatchFlag(Ljava/lang/String;)Lcom/sk89q/worldguard/protection/flags/Flag;
23.02 17:18:03 [Server] INFO at me.vik1395.ProtectionStones.FlagHandler.setFlag(FlagHandler.java:16) ~[?:?]
23.02 17:18:03 [Server] INFO at me.vik1395.ProtectionStones.Main.onCommand(Main.java:492) ~[?:?]
23.02 17:18:03 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[paperspigot-1.11.2.jar:git-Paper-1021]
23.02 17:18:03 [Server] INFO ... 15 more

Send

**Comment by ElkpojoacoTwo** [comment]
Same

**Comment by Dragoboss** [comment]
You guys are using WorldGuard 6.1.3 or up,
Use this version:
https://github.com/vik1395/ProtectionStones-Minecraft/blob/WorldGuard_6.1.3/target/ProtectionStones-1.4.1b_wg6.1.3.jar
