### ISSUE TITLE
Disabled worlds

### ISSUE THREAD

**Issue by RTCFlyer** [vik1395/ProtectionStones-Minecraft#15]
Disabling words does not work. There is no error. I am using the protectionstones version that allows flags with paperspigot.

**Comment by RTCFlyer** [comment]
#Disable the use of pStones in certain worlds.
Worlds Denied:
    - Void
    - Parkour
    - SMP
    - buildersflat
    - world
    - world_the_end
    - world_nether

**Comment by RTCFlyer** [comment]
None of these work

**Comment by Dragoboss** [comment]
If you put a world in that list it'll mean pstones does NOT function in that world.
So is your goal to prevent usage of PStones in world, world_nether, etc etc, all 7 of those worlds?
Or was your plan to allow pstones in these 7 worlds and block them in the other worlds?

In the latter case you should switch your list around.
Furthermore, which version of Minecraft do you use and which version of PStones?

**Comment by RTCFlyer** [comment]
Basically as of now I have sponges set to protection stones, now I need to disable protection stones in the SMP world so players can use sponges like normal in that world. Or Is there a way to add a protection stone with a specific lour so then you can use normal sponges but when you use a sponge with the name "Protect" on it, only then it will be used as a protectionstone. If you have any way of doing this please inform me.

**Comment by Dragoboss** [comment]
No, I am afraid not. That is currently above my knowledge level to know how to properly do that. And with Vik1395 being... basically gone at the moment...

My best suggestion is to use a block that cannot be found/crafted in the regular worlds.
I personally use Ender-Portal Frames.

However what you can do is give your players access to /ps toggle.
When doing /ps toggle they disable protection-stone behavior and if they place a sponge while that is toggled off, the sponge will just be a sponge.
