### ISSUE TITLE
Doors/TrapDoors etc

### ISSUE THREAD

**Issue by RTCFlyer** [vik1395/ProtectionStones-Minecraft#16]
Basically doors trapdoors and other redstone items or basically just player usage items don't work UNLESS the /ps flag use is set to allow. So even the owner of the region is not able to open their door without this flag. This creates issues because then other players can open private stuff.

**Comment by Dragoboss** [comment]
I would advise setting a default flag in config for 'use allow'.

**Comment by RTCFlyer** [comment]
That would allow for other players to then use that players items, (chests doors etc.)

**Comment by Dragoboss** [comment]
If you have no other method of protection, try
use -g MEMBERS allow
In config. I'm not exactly certain about the format of this flag but there should be some form or way to apply this.

Please refer to the WorldGuard wiki.
Also /ps flag -g members allow or /ps flag members allow, to apply this to existing pstones

**Comment by RTCFlyer** [comment]
Is there a way for the protection stone to be a custom block? Like instead of a sponge it could be a sponge named "protection stone" like in green or something. So players can use a regular sponge but then use the named sponge as a protection stone.

**Comment by Dragoboss** [comment]
I believe you have asked this question before. At the moment, it is not. I am still working towards the rework which will include this.
I have also advised you to use blocks that have no other uses or blocks of which the usages can be combined. For example I myself use end_portal_frame blocks. They cannot be mined, so to get them back my players use /ps reclaim. If you put them around in a square like real end-portals it doesnt seem to activate so it is not a problem.
