### ISSUE TITLE
Block sub types not recognised

### ISSUE THREAD

**Issue by LeadMagnet** [vik1395/ProtectionStones-Minecraft#20]
Trying to use MONSTER_EGGs as the PS
`Blocks: MONSTER_EGG-0,MONSTER_EGG-1,MONSTER_EGG-2,MONSTER_EGG-3,MONSTER_EGG-4,MONSTER_EGG-5`

Running WorldGuard 6.1.3 (the recommended version from another issue, jar named "worldguard-legacy-6.1.3-SNAPSHOT-dist.jar")
Have tried worldguard-6.2.jar, it works (using base blocks IE: stone), but same issue with sub type

Running PS jar labled "ProtectionStones-1.4.1b_wg6.1.3.jar"
Tried ProtectionStones-1.4.1_wg6.1.3.jar, this also works, but same issue.

The plugin works fine when using block types without sub type designations.

**Comment by LeadMagnet** [comment]
OK found the issue...

In the Minecraft Wiki, the NAME for monster eggs is listed as "monster_egg"

In the PS config file, block names are referenced in a doc (https://goo.gl/EBM8w5) as "MONSTER_EGGS"

I added the "S" to the blocks and configs and it started working. Using ProtectionStones-1.4.1b_wg6.1.3.jar and worldguard-legacy-6.1.3-SNAPSHOT-dist.jar

Still consider this a minor issue.

**Comment by Dragoboss** [comment]
Yeah. I am sorry, there is not extremely much I can change about this.
The name shown on the wiki is probably old, before spawn eggs were added.
Bukkit/Spigot has referenced it as MONSTER_EGGS for long while now.
