### ISSUE TITLE
Ore mining doesen't work

### ISSUE THREAD

**Issue by ApertureDevelopment** [vik1395/ProtectionStones-Minecraft#22]
somehow PStones disallows ore-mining.
I set "COAL_ORE,LAPIS_ORE,EMERALD_ORE,DIAMOND_ORE,REDSTONE_ORE" as PStones .. strangely redstone is Farmable the others are not. Can you please explain me why? and How do I disable that?

**Comment by Dragoboss** [comment]
Please give us a pastebin of your config file?

**Comment by Dragoboss** [comment]
Also if possible more info, for example which version of pstones are you using?

**Comment by ApertureDevelopment** [comment]
The Actual version from spigotmc.org and here is the configuration: https://pastebin.com/TtPmK0C6

**Comment by Dragoboss** [comment]
Use the github version 1.4.2, update config to new format. 

Then, set Silk Touch to true, that way, ore blocks also configured as pstones, will not be turned into ore blocks upon break with silk touch, but rather the item that would drop without silk touch, should fix all issues and safeguard your pstone settings.

**Comment by ApertureDevelopment** [comment]
Ok I downloaded the 1.4.2 and let him Re-Generate the config ( as I think its easyer then updating the old one ) but the config stayd exactly the same, there is no such option of slik touch.

**Comment by ApertureDevelopment** [comment]
Well I re added the old CFG and added the slig touch flag, now PStones doesen't work at all

**Comment by Dragoboss** [comment]
Does it give any errors in the console?
Do any commands respond or nothing at all?
If you do /pl is PStones in the list and colored green?

**Comment by ApertureDevelopment** [comment]
No errors. Yes all commands respond. Plugin is enabled.

**Comment by ApertureDevelopment** [comment]
Okay the bug is still there, but now it won't allow me to change the default protectionstones :/

Pls fix asap

**Comment by Dragoboss** [comment]
What Minecraft version was this? I'll try to have a look later this afternoon. No promises on a full fix, though.

**Comment by ApertureDevelopment** [comment]
I fixed it, there was an space in the config where a space shouldn't be. I am sorry for wasting your time
