### ISSUE TITLE
Problem with the Y radius...

### ISSUE THREAD

**Issue by kunaun1234** [vik1395/ProtectionStones-Minecraft#23]
#Set Y to 0 if you want it to protect from sky to bedrock.
    Y Radius: 0

When I set the "Y" radius to 0 it doesn't protect from sky to bedrock.

**Comment by Dragoboss** [comment]
Try if setting it to - 1 have any effect. I've had this before, some versions of some server softwares don't seem to accept the 0...

**Comment by Dragoboss** [comment]
Sorry didn't mean to close it yet.

**Comment by beautifulpoison** [comment]
That worked, I came here to report the same issue. 
Tried changing it to -1 and sure enough. Thank you !
