### ISSUE TITLE
error

### ISSUE THREAD

**Issue by PhanaticD** [vik1395/ProtectionStones-Minecraft#3]
http://pastebin.com/raw/87eEMMtb

**Comment by vik1395** [comment]
I believe that's happening because your world guard plugin hasn't been updated. Try updating it to version 6.1.2

**Comment by Dragoboss** [comment]
Are you using WorldGuard 6.1.3 legacy snapshot?

This is an unofficial and so far unstable build, that has not been publicly released yet.
Please downgrade to 6.1.2 latest, as 6.1.3 removes a function we currently use to handle flags with ProtectionStones.

If that does not fix the issues I shall have to further investigate Paper support.

**Comment by PhanaticD** [comment]
yea im using whatever was latest on their build server

**Comment by Dragoboss** [comment]
Please use no build later than 
http://builds.enginehub.org/job/worldguard/9122
for now until we figured out how to work with the changed flag system in 6.1.3

This build works should work with all 1.9 and 1.10 versions, regardless of server-mod.
- [ Add support 6.1.3+ ]

**Comment by Dragoboss** [comment]
https://github.com/vik1395/ProtectionStones-Minecraft/raw/WorldGuard_6.1.3/target/ProtectionStones-1.4.1_wg6.1.3.jar

Try this build, it works with and ONLY WITH 6.1.3
Any other, earlier WorldGuard version use the regular ProtectionStones build.
