### ISSUE TITLE
Placing Blocks Over Hidden Protection Stone

### ISSUE THREAD

**Issue by WolfRawrrr** [vik1395/ProtectionStones-Minecraft#5]
Hello, this isn't so much of an issue as it is a question. I tried finding an answer on my own, but surprisingly no one seems to have raised this yet.

What happens if someone hides their stone (I have it set to autohide on place), then places another block into the same space and later on tries `/ps unhide` while the space is occupied? Well, the plugin says that the stone is already unhidden. The next `/ps hide` then hides this other block, which disappears but completely - as it cannot be brought back with `/ps unhide` again, and neither can the stone. Plugin reports an internal error and both blocks are permanently lost.

The protection, however, remains. The only way out of that is to do `/ps reclaim`

So not really anything to worry about, just something to consider. I don't think anything's broken, at least. I just wondered what would happen so I tried, and those are the results. Oh, and tested using Spigot for 1.10.2, using PS 1.4.1

**Comment by Dragoboss** [comment]
Yes. This has actually been raised already.
I made a partial fix in 1.4.1b which has not been uploaded to Spigot yet but is available on here...

https://github.com/vik1395/ProtectionStones-Minecraft/raw/master/target/ProtectionStones-1.4.1b.jar

Anyhow, to further elaborate this 'partial fix', in 1.4.1b, when you /ps hide the pstone, then put another block over it, you can no longer /ps hide again.
However when doing /ps unhide, it will cause the newly placed block to disappear still...

At this point I did not successfully manage to put a safeguard in for the newly placed block, but at least the multi /ps hide and /ps unhide problem is fixed.
Best to just keep in mind not to place anything onto the same location as the pstone or to just not /ps unhide while that block is there....

I will keep this in mind, thank you for the report.

**Comment by WolfRawrrr** [comment]
It's a tricky thing to handle to be sure. I can't think of a better way to do it than what you have done. Thanks for your time and effort, Dragoboss :)

I know this isn't the place, but is it possible to set the stone to be a custom item? For RP flavor, I want people on my server to only be able to obtain a protection stone via the sources I specify (and not craft it themselves for example). Right now I have set it to packed ice, and since my bordered map contains no ice spikes biome, I know that there's no way to obtain it normally.

**Comment by Dragoboss** [comment]
I have never tried, actually.
Basically if the custom item has a way for both the client and server to call it, I suppose.
I personally use an End-portal frame as pstone, and several Mob-egg blocks (those blocks silverfish spawn from)....

**Comment by WolfRawrrr** [comment]
Thanks :)
