### ISSUE TITLE
Mods

### ISSUE THREAD

**Issue by GoogleTan** [vik1395/ProtectionStones-Minecraft#54]
Could you add the ability to use blocks from mods (I will use Atom). For example, in the configuration file to use not DIAMOND_BLOCK but minecraft: diamond_block, or the dictionary of ores, or use id in general.

**Comment by espidev** [comment]
Which Minecraft version are you using and with which server software? Spigot doesn't natively support mods

**Comment by GoogleTan** [comment]
I will use Atom(https://gitlab.com/divinecode/atom/Atom/) 
or
 Tablecloth(http://rubukkit.org/threads/tablecloth-1-12-2-paperspigot-forge-2836-spongepowered-experimental-optional.162352/)

**Comment by espidev** [comment]
The current version of ProtectionStones does not support 1.12.2, but you can use an older version ( which does support ids)

**Comment by GoogleTan** [comment]
Can you tell me which latest version supports IDs?

**Comment by espidev** [comment]
The latest one here https://www.spigotmc.org/resources/protectionstones.10096/

**Comment by GoogleTan** [comment]
On this version config: https://pastebin.com/TitC2U5e
This config as on new version

**Comment by GoogleTan** [comment]
How do use ID's?

**Comment by espidev** [comment]
wait no sorry, I just realized that the old version also is material name specific.

**Comment by espidev** [comment]
Okay, so adding IDs would require me backporting from 1.13 to 1.12 which would take many weeks, sorry :/

**Comment by espidev** [comment]
Just try using vanilla blocks

**Comment by GoogleTan** [comment]
Thanks
