### ISSUE TITLE
http://pastebin.com/6j20Q7W9

### ISSUE THREAD

**Issue by GciesX** [vik1395/ProtectionStones-Minecraft#8]
It was problem on WG side or ProtectionStone side?

**Comment by GciesX** [comment]
http://pastebin.com/6j20Q7W9

**Comment by Dragoboss** [comment]
I find it hard to tell from a server crash stack-trace.
See if there is any other error displayed in console before the crash, please.

If there is not, please tell me which ProtectionStones version you are on and which WorldGuard version you are working with.

**Comment by GciesX** [comment]
WG 6.1
ProtectionStone 1.4.1
It's force closed when have a lot players in server.
I think it bug on some plugin

**Comment by Dragoboss** [comment]
Full WorldGuard version? WorldGuard uses three numbers. Latest stable version is 6.1.2, latest dev is 6.1.3. Which one do you use and do you experience any other errors?
